### ISSUE TITLE
缺少首頁關於此次活動的文案

### ISSUE THREAD

**Issue by david50407** [COSCUP/coscup2018-website#4]
我們需要在首頁放置關於此次活動的介紹文案，
如此一來想了解這次活動的瀏覽者就可以藉由網站認識我們

**Comment by nfsnfs** [comment]
COSCUP是由台灣開放原始碼社群聯合推動的年度研討會，起源於2006年，是台灣自由軟體運動(FOSSM)重要的推動者之一。活動包括有講座、攤位、社團同樂會等，除了邀請國際的重量級演講者之外，台灣本土的自由軟體推動者也經常在此發表演說，會議的發起人、工作人員與講者都是志願參與的志工。COSCUP的宗旨在於提供一個聯結開放原始碼開發者、使用者與推廣者的平台。希望藉由每年一度的研討會，來推動自由及開放原始碼軟體(FLOSS)。由於有許多贊助商及熱心捐助者，所有議程都是免費參加，但因會場人數限制，通常在一開放網路報名後就會立刻額滿。

開放原始碼(Open source)是在 1998 年出現的名詞，大家早已耳熟能詳。這種在網路上已經進行二、三十年的軟體開發模式之所以能成功，有許多原因。其中一個極為關鍵的因素，就是開發者與使用者的直接接觸。無屏障的交流加速了問題的回報和修補機制，而當這個機制被網路效應放大到極限時，Linus 定律就出現了：「臭蟲難逃眾人法眼」 (With enough eyeballs, all bugs are shallow) ，軟體品質因此顯著提昇。在開放原始碼的模式中，開發者和使用者中間的人不再是銷售員或客服，而是讓軟體更容易被接受的推廣者 (Promoters)，他們打包套件讓軟體更好裝、寫說明文件讓軟體更易學、辦推廣活動讓更多人接觸到好軟體、在網路上回答問題解決使用者的疑惑，而且不會把開發者藏在背後產生資訊的不對稱。

開發者(Coders)、使用者(Users) 和推廣者(Promoters)是讓自由及開放原始碼軟體發光發熱的三大支柱，這個研討會就是專為這三種人舉辦的：你可以是 A 軟體的開發者、B 軟體的推廣者、C 軟體的使用者，不論你是已經踏入自由及開放原始碼軟體領域，還是一直站在門口不知如何入門，歡迎你來參加 COSCUP — Conference for Open Source Coders, Users and Promoters!

COSCUP 研討會已經邁入第十三年了，今年的活動有點特別，除了延續去年跟首次嘗試的社群議程外，我們還特別跟 GNOME.Asia 與 openSUSE.Asia 一起合辦，今年的時間地點則是 8/11-12 在台灣科技大學國際大樓。過去，COSCUP 由各地社群共同舉辦，在眾多同好的參與之下，逐漸成長茁壯。今年除了在地社群成為議程的協力夥伴，更加上了國際社群們，希望能打造更多元的主題和議程。無論你是寫 open source 軟體的開發者、熱衷 open source 軟體的推廣者、熟悉 open source 軟體的使用者或是想了解 open source 軟體的新手，都歡迎你來參加一年一度全台最大的 COSCUP x GNOME.Asia x openSUSE.Asia。

**Comment by nfsnfs** [comment]
COSCUP is an annual conference held by Taiwanese Open source community participants since 2006. It's a major force of Free software movement advocacy in Taiwan. The event is often held with talks, sponsor and communities booths, and Birds of a feather. In addition to international speakers, many Taiwanese local Open Source contributors often give their talks here. The chief organizer, staffs, and speakers are all volunteers.

COSCUP's aim is providing a platform to connect Open Source coders, users, and promoters, and promote FLOSS with the annual conference. The conference is free to attend because of the enthusiastic sponsors and donators. Since the conference venue is limited, tickets are often sold out immediately after the online registration starts.

It is a common fact that the coders of traditional commercial software rarely interact with users.

The term "Open Source" appears in 1998, which is familiar to everyone. This kind of developing pattern working on the Internet over 20 to 30 years attributes to many reasons. The key factor may be the direct interaction with coders and users, which forms a rapid feedback and patch system on bugs. This pattern is enlarged by the Internet, where Linus's law "With enough eyeballs, all bugs are shallow" occurs, thereby the software's quality enhances. In Open Source pattern, promoters take the position between coders and users, rather than sales and customer service. They package software suites to get installation easier, write documents to lower its learning curve, hold events to spread good software, solve questions from the Internet without creating information asymmetry.

COSCUP celebrates its 13th anniversary this year. Over the past decade, the event has co-operated with communities all over the world. With everyone's involvement, COSCUP grows up. This year, COSCUP will co-host with GNOME.Asia and openSUSE.Asia in National Taiwan University of Science and Technology on 8/11-8/12. And several communities will be the program partners to provide diversified topics and talks. 

Whoever you are a Open Source coder, a devoted Open Source promoter, a user familiar with Open Source, or even a newcomer, we sincerely welcome you to be a part of COSCUP!

**Comment by nfsnfs** [comment]
拿去年的稍微改一下，如果沒問題的話就先上？有人想改再改就好。

**Comment by david50407** [comment]
also fixed at https://github.com/COSCUP/coscup2018-website/commit/0d66bb7337da91a7440d69d65268909bbf45838c

**Comment by david50407** [comment]
中文的部分我調整了一下空白的位置， @nfsnfs 你可以再幫我確認這樣是不是有比較好讀？
